version: '3.3'

#Внимание! Не LOG_FILE! Он не перезаписывает application.yml

services:
  vkrattach:
    image: vkrattach:0.1
    container_name: my-vkrattach-container
    environment:
      - LOGGING_FILE_PATH=/application/logs
      - LOGGING_FILE_NAME=logs
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/application/data/data
      - SPRING_SQL_INIT_MODE=never
    ports:
      - "80:8080"
    restart: unless-stopped
    volumes:
      - /root/logs:/application/logs
      - /root/data:/application/data
