spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vkrattach
    username: postgres
    password: 11111
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate.ejb.interceptor: ru.bk.artv.vkrattach.config.EmptyStringInterceptor
  profiles:
    include: user
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/resources/templates/
jwt:
  cookie-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'

logging:
  file:
    name: mylog.log
  level:
    ru.artv.bk.vkrattach: INFO
    org:
      springframework:
#        security: trace
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

server:
  port: 8080
  servlet:
    session:
      timeout: 24h

