spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vkr_attach
    username: postgres
    password: 11111
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false
  profiles:
    include: user

logging:
  file:
    name: mylog.log
  level:
    ru.artv.bk.vkrattach: INFO
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

server:
  port: 8080

