vkrattach:
  users:
#    обязательно разделять знаком = и без пробелов. Просто добавляет строчку в список, потому что русские буквы
#    не поддерживаются в качестве ключа MAP
    faculties:
      - НБФЗОП=40.05.01 Правовое обеспечение национальной безопасности
      - ПФЗОП=40.05.02 Правоохранительная деятельность
      - ЮВФЗОМ=40.04.01 Юриспруденция (магистратура)
    yearOfRecruitment:
      - 2017
      - 2018
      - 2019
      - 2020
      - 2021
      - 2022
      - 2023
      - 2024
      - 2025
    departments:
      UPV: Уголовного права
      UPR: Уголовного процесса
      CRIMINOLOGY: Криминологии
      CRIMINALISTICS: Криминалистики
      ADMINISTRATIVE_LAW: Административного права и административной деятельности органов внутренних дел
      TGP: Теории государства и права
      ORD: Оперативно-розыскной деятельности органов внутренних дел