#---
#spring:
#  profiles: prod

---
spring:
  config:
    activate:
      on-profile: test-h2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: classpath:sql/1-schema-h2.sql
      data-locations: classpath:sql/2-data-lecturer.sql, classpath:sql/3-data-theme.sql, classpath:sql/4-data-user.sql, classpath:sql/5-data-order.sql, classpath:sql/6-config-data.sql
logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: trace
---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/vkrattach
    username: postgres
    password: 11111
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: classpath:sql/1-schema-postgres.sql
      data-locations: classpath:sql/2-data-lecturer.sql, classpath:sql/3-data-theme.sql, classpath:sql/4-data-user.sql,classpath:sql/5-data-order.sql, classpath:sql/6-config-data.sql
      mode: always
logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: trace
