vkrattach:
  users:
#    обязательно разделять знаком = и без пробелов
    faculties:
      - НБФЗОП=40.05.01 Правовое обеспечение национальной безопасности
      - ПФЗОП=40.05.02 Правоохранительная деятельность
      - ЮВФЗОС=40.03.01 Юриспруденция (на базе высшего неюридического образования)
      - ЮВФЗОМ=40.04.01 Юриспруденция (магистратура)
    yearOfRecruitment:
      - 2017
      - 2018
      - 2019
      - 2020
      - 2021
      - 2022
      - 2023
      - 2024
      - 2025