spring:
  jpa:
    properties:
      hibernate.ejb.interceptor: ru.bk.artv.vkrattach.config.EmptyStringInterceptor
  profiles:
    include: profiles, keys
    active: dev-h2
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/templates/static
  sql:
    init:
      encoding: utf-8
logging:
  file:
    path: c:/temp/logs
    name: logs
  level:
    ru.bk.artv.vkrattach: INFO
    org:
      springframework:
        security: INFO
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO

server:
  port: 8080